//! `sim_arena::generator`, the loop that writes a policy the registry can see. The registry is
//! generated by `crates/sim-policy/build.rs` from line 1 of each file, and a file whose header is
//! malformed is either silently not a policy or a build panic; so the first test re-implements that
//! parser's rules rather than importing a build script, and holds every variant to them.

mod common;

use lbsim::arena::catalog::{append, HEADER};
use lbsim::arena::generator::{catalog_row, render, sha256_hex, write_policy, VARIANTS};

const CATALOG: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/docs/policy-catalog.md");

fn temp_dir(tag: &str) -> common::ScratchDir {
    common::scratch(&format!("arena-generator-{tag}"))
}

/// `build.rs::parse_header`, restated: prefix, a kind token in {routing, admission}, `names=` non-empty.
fn parse_header(line: &str) -> Option<(String, Vec<String>)> {
    let rest = line.trim().strip_prefix("//! lbsim-policy:")?.trim();
    let mut kind = None;
    let mut names = Vec::new();
    for tok in rest.split_whitespace() {
        if let Some(v) = tok.strip_prefix("names=") {
            names = v.split(',').filter(|s| !s.is_empty()).map(str::to_string).collect();
        } else {
            kind = Some(tok.to_string());
        }
    }
    let kind = kind?;
    if kind != "routing" && kind != "admission" || names.is_empty() {
        return None;
    }
    Some((kind, names))
}

#[test]
fn generated_policy_carries_the_registry_header() {
    let dir = temp_dir("header");
    assert!(!VARIANTS.is_empty());
    for v in VARIANTS {
        let (path, _) = write_policy(&dir, v).unwrap();
        assert_eq!(path.file_name().unwrap().to_str().unwrap(), format!("gen_{}.rs", v.name));
        let text = std::fs::read_to_string(&path).unwrap();
        let first = text.lines().next().unwrap_or("");
        assert_eq!(first, format!("//! lbsim-policy: {} names={}", v.family, v.name));
        let (kind, names) = parse_header(first).unwrap_or_else(|| panic!("{}: header rejected", v.name));
        assert_eq!(kind, v.family);
        assert_eq!(names, vec![v.name.to_string()]);
        // The module name is the file stem, and the registry's `mod` line needs a legal identifier.
        let stem = path.file_stem().unwrap().to_str().unwrap();
        assert!(stem.chars().all(|c| c.is_ascii_alphanumeric() || c == '_'), "{stem}");
    }
}

#[test]
fn generated_source_hash_is_stable() {
    // Known vectors first, so a wrong constant in the hand-written SHA-256 fails here and not in a
    // catalog row nobody rechecks.
    assert_eq!(sha256_hex(b""), "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855");
    assert_eq!(sha256_hex(b"abc"), "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad");
    // 56 bytes: the padding case where the length no longer fits the first block.
    assert_eq!(
        sha256_hex(b"abcdbcdecdefdefgefghfghighijhijkijkljklmklmnlmnomnopnopq"),
        "248d6a61d20638b8e5c026930c3e6039a33ce45964ff2167f6ecedd419db06c1"
    );

    let dir = temp_dir("hash");
    let mut seen = Vec::new();
    for v in VARIANTS {
        let (_, first) = write_policy(&dir, v).unwrap();
        let (_, second) = write_policy(&dir, v).unwrap();
        assert_eq!(first, second, "{}: same variant, different hash", v.name);
        assert_eq!(first, sha256_hex(render(v).as_bytes()));
        assert_eq!(first.len(), 64);
        assert!(!seen.contains(&first), "{}: hash collides with another variant", v.name);
        seen.push(first);
    }
}

#[test]
fn catalog_row_is_appended_once() {
    let dir = temp_dir("catalog");
    let catalog = dir.join("policy-catalog.md");
    std::fs::copy(CATALOG, &catalog).unwrap();
    let before = std::fs::read_to_string(&catalog).unwrap();
    let headers = |t: &str| t.lines().filter(|l| l.starts_with(HEADER)).count();

    let v = &VARIANTS[0];
    let (path, hash) = write_policy(&dir, v).unwrap();
    let row = catalog_row(v, &path, &hash, 0.5, "2026-09-06");
    assert_eq!(row.rule_set, lbsim::arena::RULE_SET);
    assert!(row.source.ends_with(&format!("@{}", &hash[..12])), "{}", row.source);

    append(&catalog, &row).unwrap();
    append(&catalog, &row).unwrap();

    let after = std::fs::read_to_string(&catalog).unwrap();
    let rows = after.lines().filter(|l| l.starts_with(&format!("| `{}` |", v.name))).count();
    assert_eq!(rows, 1, "the row was appended {rows} times");
    assert!(headers(&after) >= 1);
    assert!(headers(&after) >= headers(&before), "a table lost its header");
    assert!(after.contains(&row.source));
}
