//! The prefix model, engine half: a tree of shared prefixes generated by the workload, a per-replica
//! prefix cache with an LRU under a token budget, the fleet-wide index a router keys on, and the
//! per-window hit accounting. All of it is off by default, and the last test pins that.

mod common;

use lbsim::model::{PrefixTree, Replica};
use lbsim::physics::CostModel;
use lbsim::scenario::Scenario;
use lbsim::sim::{self, PrefixHolders, Sim};
use lbsim::workload::Request;
use lbsim::{Nanos, EPOCH_BASE, SECOND};

/// One replica, one root, and arrivals sparse enough that the first frame holds only the first
/// request, whose prefill must be a miss against a cold cache.
fn one_root() -> Scenario {
    let mut s = common::small();
    s.replicas = 1;
    s.arrival_rps = 1.0;
    s.duration_s = 20.0;
    s.warmup_s = 0.0;
    s.sample_interval_ms = 50.0;
    s.prefix_roots = 1;
    s.prefix_cache_tokens = 1e6;
    s
}

fn run_to_end(sc: &Scenario) -> Sim {
    let mut sim = Sim::new(sc).unwrap();
    let end = sim.end();
    sim.advance_to(end).unwrap();
    sim
}

#[test]
fn first_request_misses_and_later_ones_hit_at_most_the_root() {
    let sc = one_root();
    let sim = run_to_end(&sc);
    let root_tokens = sim.prefix_tree().path_tokens(1);
    assert!(root_tokens > 0, "a root has a length");
    let first = sim.frames().iter().find(|f| f.replicas[0].prompt_tokens > 0).expect("an admission");
    assert_eq!(first.replicas[0].prefix_hit_tokens, 0, "the cold cache cannot hit");
    let hits: u64 = sim.frames().iter().map(|f| f.replicas[0].prefix_hit_tokens).sum();
    assert!(hits > 0, "every later request shares the root and must hit");
    for f in sim.frames() {
        let r = &f.replicas[0];
        assert!(r.prefix_hit_tokens <= r.prompt_tokens, "a hit is part of the prompt");
    }
    let admitted = sim.records().len() as u64;
    assert!(hits <= admitted * root_tokens as u64, "a hit is at most the shared root");
}

#[test]
fn a_budget_below_the_root_never_hits() {
    let mut sc = one_root();
    sc.prefix_cache_tokens = 10.0;
    let sim = run_to_end(&sc);
    assert!(sim.prefix_tree().path_tokens(1) > 10);
    let hits: u64 = sim.frames().iter().map(|f| f.replicas[0].prefix_hit_tokens).sum();
    assert_eq!(hits, 0, "nothing fits, so nothing is ever resident");
    let prompts: u64 = sim.frames().iter().map(|f| f.replicas[0].prompt_tokens).sum();
    assert!(prompts > 0);
}

fn req(id: u64, node: u64, tree: &PrefixTree) -> Request {
    let prefix_tokens = tree.path_tokens(node);
    Request {
        id,
        arrived_at: EPOCH_BASE,
        attempt_at: EPOCH_BASE,
        prompt: prefix_tokens + 100,
        output: 2,
        attempts: 1,
        deadline: EPOCH_BASE + 60 * SECOND,
        is_long: false,
        tenant: 0,
        class: 0,
        prefix_node: node,
        prefix_tokens,
    }
}

/// Run one request through an otherwise idle replica to completion.
fn serve(r: &mut Replica, sc: &Scenario, cost: &CostModel, tree: &PrefixTree, now: &mut Nanos, req: Request) {
    r.enqueue(req, sc.max_queue).ok().unwrap();
    r.wake(*now);
    for _ in 0..1000 {
        let Some(out) = r.step_with_prefixes(sc, cost, *now, tree) else { return };
        *now = out.token_at;
        if out.idle {
            return;
        }
    }
    panic!("request never finished");
}

/// Three roots of 100 tokens and a budget for two.
fn three_roots() -> (Scenario, PrefixTree) {
    let mut sc = Scenario::default();
    sc.prefix_cache_tokens = 250.0;
    let mut tree = PrefixTree::new(&sc, &mut lbsim::rng::Rng::from_seed(1));
    for _ in 0..3 {
        tree.child(0, 100);
    }
    (sc, tree)
}

#[test]
fn lru_keeps_the_more_recently_used_root() {
    let (sc, tree) = three_roots();
    let cost = sc.cost_model();
    let mut r = Replica::default();
    let mut now = EPOCH_BASE;

    serve(&mut r, &sc, &cost, &tree, &mut now, req(1, 1, &tree));
    assert_eq!(r.drain_prefix_changes(), (vec![1], vec![]));
    assert_eq!(r.prefix_hit(&tree, 1), 100);

    serve(&mut r, &sc, &cost, &tree, &mut now, req(2, 2, &tree));
    assert_eq!(r.drain_prefix_changes(), (vec![2], vec![]));
    assert_eq!(r.prefix_cache_tokens(), 200);

    // Root 1 again: a hit, which refreshes it, so root 2 is now the least recently used.
    serve(&mut r, &sc, &cost, &tree, &mut now, req(3, 1, &tree));
    assert_eq!(r.drain_prefix_changes(), (vec![], vec![]));
    assert_eq!(r.prefix_hit_tokens_total(), 100, "the third request reused the root");

    serve(&mut r, &sc, &cost, &tree, &mut now, req(4, 3, &tree));
    let (inserted, evicted) = r.drain_prefix_changes();
    assert_eq!(inserted, vec![3]);
    assert_eq!(evicted, vec![2], "the root used least recently goes, not the one inserted first");
    assert_eq!(r.prefix_hit(&tree, 1), 100);
    assert_eq!(r.prefix_hit(&tree, 2), 0);
    assert_eq!(r.prefix_hit(&tree, 3), 100);
    assert_eq!(r.prefix_cache_tokens(), 200);
}

#[test]
fn holders_follow_prefill_and_eviction() {
    let (sc, mut tree) = three_roots();
    let cost = sc.cost_model();
    let mut r = Replica::default();
    let mut now = EPOCH_BASE;
    let mut holders = PrefixHolders::default();
    let turn = tree.child(1, 300);

    assert!(holders.holders(&tree, 1).is_empty(), "nothing is resident before any prefill");
    serve(&mut r, &sc, &cost, &tree, &mut now, req(1, 1, &tree));
    let (ins, ev) = r.drain_prefix_changes();
    holders.apply(3, &ins, &ev);
    assert_eq!(holders.holders(&tree, 1), vec![(3, 100)]);
    assert_eq!(holders.holders(&tree, turn), vec![(3, 100)], "a deeper node falls back to its held ancestor");
    assert!(holders.holders(&tree, 2).is_empty());

    // Two more roots push the first out of a two-root budget.
    serve(&mut r, &sc, &cost, &tree, &mut now, req(2, 2, &tree));
    serve(&mut r, &sc, &cost, &tree, &mut now, req(3, 3, &tree));
    let (ins, ev) = r.drain_prefix_changes();
    holders.apply(3, &ins, &ev);
    assert!(holders.holders(&tree, 1).is_empty(), "evicted, so no longer held");
    assert!(holders.holders(&tree, turn).is_empty());
    assert_eq!(holders.holders(&tree, 2), vec![(3, 100)]);

    // A crash empties the cache, and the index hears of it.
    r.crash();
    let (ins, ev) = r.drain_prefix_changes();
    holders.apply(3, &ins, &ev);
    assert!(holders.holders(&tree, 2).is_empty());
    assert!(holders.holders(&tree, 3).is_empty());
}

/// Turns extend their previous turn's node and forks reuse a finished request's, so the tree grows
/// past its roots and the hits go on, on a fleet rather than one replica.
#[test]
fn turns_and_forks_grow_the_tree_and_hit() {
    let mut sc = one_root();
    sc.replicas = 2;
    sc.arrival_rps = 4.0;
    sc.prefix_roots = 5;
    sc.session_turns_mean = 3.0;
    sc.session_think_s = 0.5;
    sc.session_fork_rate = 0.3;
    let sim = run_to_end(&sc);
    assert!(sim.prefix_tree().nodes() > 6, "session turns add nodes under the roots");
    let hits: u64 = sim.frames().iter().flat_map(|f| f.replicas.iter().map(|r| r.prefix_hit_tokens)).sum();
    assert!(hits > 0);
    for f in sim.frames() {
        for r in &f.replicas {
            assert!(r.prefix_hit_tokens <= r.prompt_tokens);
        }
    }
    assert!(sim.records().iter().any(|r| r.id >= 1 << 40), "some session turns ran");
}

/// Every prefix key at its default is the run that was there before the prefix model existed.
/// Recorded from `origin/master` before this unit; `check-fingerprints.sh` pins the same fleet-wide.
#[test]
fn defaults_leave_the_baseline_run_untouched() {
    let sc = common::small();
    assert_eq!(sc.prefix_roots, 0);
    assert_eq!(sc.prefix_cache_tokens, 0.0);
    assert_eq!(sc.session_fork_rate, 0.0);
    let r = sim::run(&sc).unwrap();
    assert_eq!(r.events, 17777);
    assert_eq!(r.records.len(), 522);
    assert_eq!(r.fingerprint, 0xbcc627de068bbeeb);
}
