//! Shared scenario fixtures for the integration tests.
//!
//! Everything here is deliberately tiny: 8 replicas and tens of simulated seconds. The properties
//! under test are structural, not statistical, so a big scenario would buy nothing but wall time.

#![allow(dead_code)]

use lbsim::metrics::RequestRecord;
use lbsim::scenario::Scenario;
use lbsim::sim::RunResult;
use lbsim::{Nanos, EPOCH_BASE};
use std::collections::BTreeMap;

/// The standard small fleet. 8 replicas, 30 simulated seconds, 3 s of warmup.
pub fn small() -> Scenario {
    let mut s = Scenario::default();
    s.name = "test_small".into();
    s.seed = 42;
    s.replicas = 8;
    s.max_batch = 16;
    s.duration_s = 30.0;
    s.warmup_s = 3.0;
    s.client_timeout_s = 8.0;
    s.routing = "p2c".into();
    // Pinned rather than derived from Scenario::default(): the fixture is 20 rps on 8 replicas, and
    // the fingerprints tests pin against it must not move when the demo default fleet does.
    s.arrival_rps = 20.0; // overwritten by most callers
    s
}

/// `small()` with the arrival rate set to a fraction of rated capacity, so the tests are expressed
/// in load units rather than in a magic rps that silently drifts when the cost model is recalibrated.
pub fn at_load(fraction: f64) -> Scenario {
    let mut s = small();
    s.arrival_rps = fraction * s.rated_rps();
    s
}

/// The last arrival time that is *guaranteed* to have produced a record.
///
/// A record only exists once a request terminates, and the run stops hard at `duration_s`. Any
/// request arriving later than `duration_s - client_timeout_s` may still be in flight when the run
/// ends and would then be missing from `records` — through no fault of the workload. Comparing
/// workloads across runs is only meaningful inside this window.
pub fn settled_window(s: &Scenario) -> (Nanos, Nanos) {
    let lo = EPOCH_BASE + (s.warmup_s * 1e9) as Nanos;
    let hi = EPOCH_BASE + ((s.duration_s - s.client_timeout_s) * 1e9) as Nanos;
    assert!(hi > lo, "settled window is empty; raise duration_s or lower client_timeout_s");
    (lo, hi)
}

pub fn settled<'a>(r: &'a RunResult, s: &Scenario) -> Vec<&'a RequestRecord> {
    let (lo, hi) = settled_window(s);
    r.records
        .iter()
        .filter(|x| x.arrived_at >= lo && x.arrived_at <= hi)
        .collect()
}

/// Multiset of request shapes, as generated by the workload.
pub fn shape_multiset(recs: &[&RequestRecord]) -> BTreeMap<(u32, u32), u32> {
    let mut m = BTreeMap::new();
    for r in recs {
        *m.entry((r.prompt_tokens, r.output_tokens)).or_insert(0) += 1;
    }
    m
}

pub fn prompt_multiset(recs: &[&RequestRecord]) -> BTreeMap<u32, u32> {
    let mut m = BTreeMap::new();
    for r in recs {
        *m.entry(r.prompt_tokens).or_insert(0) += 1;
    }
    m
}

pub fn arrival_times(recs: &[&RequestRecord]) -> Vec<Nanos> {
    let mut v: Vec<Nanos> = recs.iter().map(|r| r.arrived_at).collect();
    v.sort_unstable();
    v
}
