import { DATA_SOURCE_GLOSS } from '../lib/mode';

export function Home() {
  return (
    <div className="home">
      <h1>lbsim</h1>
      <p className="lede">
        A discrete-event simulator for a cloud LLM inference service. This is the stand-in dashboard: the layout, the
        tab structure and the pagination story, running against mock data generated in this browser so they can be
        criticised before anything is wired to a server.
      </p>

      <ul className="surfaces">
        <li>
          <a href="#/dashboard">Load test dashboard</a>
          <p>
            The fully customisable playground. Playback across the top, control panel left, observation suite right.
            Tune load and policy while it runs and watch what changes. <code>#/dashboard</code>
          </p>
          <p className="tag-line">
            <b>live</b> when the server answers, else <b>replay</b>, else <b>mock</b> &mdash; live is{' '}
            {DATA_SOURCE_GLOSS.live}, replay is {DATA_SOURCE_GLOSS.replay}, mock is {DATA_SOURCE_GLOSS.mock}.
          </p>
        </li>
        <li>
          <a href="#/ab">A/B view</a>
          <p>
            The same load and the same seed, two policies side by side. Refuses to compare two runs that differ in
            anything but the policy, and says which field stopped it. <code>#/ab</code>
          </p>
          <p className="tag-line">
            always <b>mock</b> &mdash; {DATA_SOURCE_GLOSS.mock}; both sides run the same mock engine.
          </p>
        </li>
        <li>
          <a href="#/showcase">Showcase</a>
          <p>
            One card per interesting dynamic. Clicking one runs a scripted walkthrough that advances the run, pauses at
            the moments that matter and says what to look at. <code>#/showcase</code>
          </p>
          <p className="tag-line">
            <b>replay</b> or <b>live</b> per walkthrough, else <b>mock</b> when neither is available.
          </p>
        </li>
      </ul>

      <h2>Reports from the real engine</h2>
      <p className="lede">
        Six self-contained HTML reports, generated by <code>sim-run</code> when this site was built and served from
        the same origin. These are the numbers in <code>docs/findings.md</code>, not mock data: every one is
        reproducible from the scenario printed at the bottom of its page.{' '}
        <b>report &mdash; real engine output (a replay, not live)</b>: {DATA_SOURCE_GLOSS.replay}, recorded once and
        served as a static file, never re-run on the fly.
      </p>
      <ul className="surfaces">
        <li>
          <a href="reports/1-routing.html">1. Reading the whole fleet is worse than sampling two of it</a>
          <p>Four routing policies at identical load and seed. <code>reports/1-routing.html</code> &middot; report</p>
        </li>
        <li>
          <a href="reports/2-staleness.html">2. Herding is a smooth function of staleness, and it is steep</a>
          <p>Telemetry interval swept from 100 ms to 4 s. <code>reports/2-staleness.html</code> &middot; report</p>
        </li>
        <li>
          <a href="reports/3-chunking.html">3. Prefill and decode contend for one device, and no setting wins both</a>
          <p>Chunked-prefill budget swept from 512 to 16,384 tokens. <code>reports/3-chunking.html</code> &middot; report</p>
        </li>
        <li>
          <a href="reports/4-load-curve.html">4. Past the knee, offering more load delivers less work</a>
          <p>Offered load swept from 30 to 230 requests per second. <code>reports/4-load-curve.html</code> &middot; report</p>
        </li>
        <li>
          <a href="reports/5-long-context.html">
            5. Capacity is a token budget, and a load-balancer metric can improve while service collapses
          </a>
          <p>Long-context share swept from 0 to 32%. <code>reports/5-long-context.html</code> &middot; report</p>
        </li>
        <li>
          <a href="reports/6-retry.html">6. A retry budget is the difference between a bad minute and an outage</a>
          <p>
            No retries, a retry budget, and a retry storm, after the same load spike. <code>reports/6-retry.html</code>{' '}
            &middot; report
          </p>
        </li>
      </ul>

      <div className="footnote">
        <h2>What you are looking at</h2>
        <p>
          The engine does not exist yet, so every number here is invented by <code>web/src/lib/engine.ts</code> and
          every panel says so. The mock is arranged so the directions are right rather than the magnitudes: raising the
          arrival rate raises queue depth and then latency; round robin with a heavy tail produces a hotspot that walks
          the fleet; power-of-two-choices does not. That is enough to judge a layout and not enough to draw a
          conclusion about a policy.
        </p>
        <p>
          The shapes match <code>proto/lbsim/v1</code>: metrics are the <code>Metric</code> enum, distributions are
          bucketed histograms merged bucket-wise, a subscription names exactly one entity, and the responses that carry
          information the user is owed &mdash; where a step stopped, whether a rewind came from the recorded log,
          whether an update forced re-simulation &mdash; are surfaced rather than swallowed. See{' '}
          <code>web/README.md</code> for what has to change when <code>sim-ingress</code> exists.
        </p>
      </div>
    </div>
  );
}
