//! The arena generator loop, U34: render a policy from a template, hash it, and with `--keep` build,
//! score and catalog it. `docs/arena.md` section 6 wants the generator to write real code; the
//! forecasting families that would make that interesting are U40 and not built, so the variants here
//! are deliberately plain p2c relatives. The *loop* is the unit: every step a later generator needs
//! is exercised end to end, and only the template gets smarter.
//!
//! Two processes, not one. The policy registry is generated by `sim-policy/build.rs` from the files in
//! `crates/sim-policy/src/`, so a name written by this process does not resolve in this process. With
//! `--keep` the parent writes the file and rebuilds, then re-invokes the freshly built binary with
//! `--score`, and that child is the one that runs the round and appends the catalog row. Without
//! `--keep` the loop stops after the file and its hash, which is what the tests exercise.
//!
//! Nothing here draws randomness and nothing reads a clock: the catalog date comes from `--date`.

use crate::catalog::{append, CatalogRow};
use crate::{holdout_suite, run_round, RoundConfig, RULE_SET};
use std::path::{Path, PathBuf};
use std::process::Command;

/// One template instantiation. `key` is the `ReplicaView` field the policy minimises and `d` the
/// number of replicas it samples; together they cover every variant shipped today.
pub struct Variant {
    pub name: &'static str,
    pub family: &'static str,
    pub idea: &'static str,
    key: &'static str,
    d: usize,
}

pub const VARIANTS: &[Variant] = &[
    Variant {
        name: "p2c_d3",
        family: "routing",
        idea: "p2c with d fixed at 3: one more sample than the default, same staleness robustness",
        key: "queued_tokens",
        d: 3,
    },
    Variant {
        name: "p2c_d4",
        family: "routing",
        idea: "p2c with d fixed at 4: closer to least-loaded, more exposed to a stale idle replica",
        key: "queued_tokens",
        d: 4,
    },
    Variant {
        name: "least_kv_p2c",
        family: "routing",
        idea: "p2c keyed on resident kv_tokens rather than queued_tokens: the load in the unit that fills",
        key: "kv_tokens",
        d: 2,
    },
];

pub fn variant(family: &str, name: &str) -> Result<&'static Variant, String> {
    VARIANTS.iter().find(|v| v.family == family && v.name == name).ok_or_else(|| {
        let known: Vec<&str> = VARIANTS.iter().filter(|v| v.family == family).map(|v| v.name).collect();
        format!("no variant {name:?} in family {family:?}; known: {}", known.join(", "))
    })
}

/// `least_kv_p2c` becomes `LeastKvP2c`, a legal and readable type name.
fn type_name(variant: &str) -> String {
    variant
        .split('_')
        .map(|w| {
            let mut c = w.chars();
            match c.next() {
                Some(f) => f.to_uppercase().collect::<String>() + c.as_str(),
                None => String::new(),
            }
        })
        .collect()
}

/// The policy source. Line 1 is the registry header `build.rs` parses, byte for byte.
pub fn render(v: &Variant) -> String {
    let ty = type_name(v.name);
    let Variant { name, family, idea, key, d } = v;
    format!(
        r#"//! lbsim-policy: {family} names={name}
//! Generated by `sim-run generate --family {family} --variant {name}`. Regenerate rather than edit.
//!
//! {idea}.

use crate::{{RouteContext, RoutingPolicy}};
use sim_scenario::Scenario;

pub struct {ty};

pub fn make(_sc: &Scenario) -> Box<dyn RoutingPolicy> {{
    Box::new({ty})
}}

impl RoutingPolicy for {ty} {{
    fn label(&self) -> String {{
        "{name}".to_string()
    }}
    fn inspected(&self, _fleet: usize) -> usize {{
        {d}
    }}
    fn choose(&mut self, ctx: &mut RouteContext<'_>) -> Option<usize> {{
        let n = ctx.fleet();
        if n == 0 {{
            return None;
        }}
        let mut best: Option<usize> = None;
        let mut best_key = u64::MAX;
        for _ in 0..{d} {{
            let i = ctx.rng.below(n as u64) as usize;
            if !ctx.usable(i) {{
                continue;
            }}
            let key = ctx.views[i].{key};
            if key < best_key || (key == best_key && Some(i) < best) {{
                best_key = key;
                best = Some(i);
            }}
        }}
        best.or_else(|| ctx.first_usable())
    }}
}}
"#
    )
}

/// Write the variant to `dir/gen_<name>.rs` and return the path with the source hash.
pub fn write_policy(dir: &Path, v: &Variant) -> Result<(PathBuf, String), String> {
    let source = render(v);
    let path = dir.join(format!("gen_{}.rs", v.name));
    std::fs::create_dir_all(dir).map_err(|e| format!("{}: {e}", dir.display()))?;
    std::fs::write(&path, &source).map_err(|e| format!("{}: {e}", path.display()))?;
    Ok((path, sha256_hex(source.as_bytes())))
}

/// The catalog's `Source` column: where the code is and which code it was.
pub fn source_ref(path: &Path, hash: &str) -> String {
    format!("{}@{}", path.display(), &hash[..12.min(hash.len())])
}

pub fn catalog_row(v: &Variant, path: &Path, hash: &str, score: f64, date: &str) -> CatalogRow {
    CatalogRow {
        name: v.name.to_string(),
        family: v.family.to_string(),
        idea: v.idea.to_string(),
        source: source_ref(path, hash),
        score,
        rule_set: RULE_SET.to_string(),
        added: date.to_string(),
    }
}

/// SHA-256, FIPS 180-4, standard library only: the workspace takes no dependency for forty lines.
pub fn sha256_hex(data: &[u8]) -> String {
    const K: [u32; 64] = [
        0x428a2f98, 0x71374491, 0xb5c0fbcf, 0xe9b5dba5, 0x3956c25b, 0x59f111f1, 0x923f82a4, 0xab1c5ed5,
        0xd807aa98, 0x12835b01, 0x243185be, 0x550c7dc3, 0x72be5d74, 0x80deb1fe, 0x9bdc06a7, 0xc19bf174,
        0xe49b69c1, 0xefbe4786, 0x0fc19dc6, 0x240ca1cc, 0x2de92c6f, 0x4a7484aa, 0x5cb0a9dc, 0x76f988da,
        0x983e5152, 0xa831c66d, 0xb00327c8, 0xbf597fc7, 0xc6e00bf3, 0xd5a79147, 0x06ca6351, 0x14292967,
        0x27b70a85, 0x2e1b2138, 0x4d2c6dfc, 0x53380d13, 0x650a7354, 0x766a0abb, 0x81c2c92e, 0x92722c85,
        0xa2bfe8a1, 0xa81a664b, 0xc24b8b70, 0xc76c51a3, 0xd192e819, 0xd6990624, 0xf40e3585, 0x106aa070,
        0x19a4c116, 0x1e376c08, 0x2748774c, 0x34b0bcb5, 0x391c0cb3, 0x4ed8aa4a, 0x5b9cca4f, 0x682e6ff3,
        0x748f82ee, 0x78a5636f, 0x84c87814, 0x8cc70208, 0x90befffa, 0xa4506ceb, 0xbef9a3f7, 0xc67178f2,
    ];
    let mut h: [u32; 8] =
        [0x6a09e667, 0xbb67ae85, 0x3c6ef372, 0xa54ff53a, 0x510e527f, 0x9b05688c, 0x1f83d9ab, 0x5be0cd19];
    let mut msg = data.to_vec();
    msg.push(0x80);
    while msg.len() % 64 != 56 {
        msg.push(0);
    }
    msg.extend_from_slice(&((data.len() as u64) * 8).to_be_bytes());
    for chunk in msg.chunks(64) {
        let mut w = [0u32; 64];
        for (i, word) in chunk.chunks(4).enumerate() {
            w[i] = u32::from_be_bytes([word[0], word[1], word[2], word[3]]);
        }
        for i in 16..64 {
            let s0 = w[i - 15].rotate_right(7) ^ w[i - 15].rotate_right(18) ^ (w[i - 15] >> 3);
            let s1 = w[i - 2].rotate_right(17) ^ w[i - 2].rotate_right(19) ^ (w[i - 2] >> 10);
            w[i] = w[i - 16].wrapping_add(s0).wrapping_add(w[i - 7]).wrapping_add(s1);
        }
        let [mut a, mut b, mut c, mut d, mut e, mut f, mut g, mut hh] = h;
        for i in 0..64 {
            let s1 = e.rotate_right(6) ^ e.rotate_right(11) ^ e.rotate_right(25);
            let ch = (e & f) ^ (!e & g);
            let t1 = hh.wrapping_add(s1).wrapping_add(ch).wrapping_add(K[i]).wrapping_add(w[i]);
            let s0 = a.rotate_right(2) ^ a.rotate_right(13) ^ a.rotate_right(22);
            let maj = (a & b) ^ (a & c) ^ (b & c);
            let t2 = s0.wrapping_add(maj);
            hh = g;
            g = f;
            f = e;
            e = d.wrapping_add(t1);
            d = c;
            c = b;
            b = a;
            a = t1.wrapping_add(t2);
        }
        for (slot, v) in h.iter_mut().zip([a, b, c, d, e, f, g, hh]) {
            *slot = slot.wrapping_add(v);
        }
    }
    h.iter().map(|x| format!("{x:08x}")).collect()
}

const KEEP_DIR: &str = "crates/sim-policy/src";
const CATALOG: &str = "docs/policy-catalog.md";
const BUILD: &str = "tools/build.sh";

fn run(step: &str, cmd: &mut Command) -> Result<(), String> {
    eprintln!("generate: {step}: {cmd:?}");
    let status = cmd.status().map_err(|e| format!("{step}: {e}"))?;
    if status.success() {
        Ok(())
    } else {
        Err(format!("{step} failed: {status}"))
    }
}

/// `sim-run generate --family F --variant V [--dir DIR] [--keep --date YYYY-MM-DD] [--catalog PATH]`.
///
/// `--score` is the child's half of the `--keep` loop and is not meant to be typed: it asserts the
/// file on disk is the source it would render, runs the round, and appends the catalog row.
pub fn generate_main(args: Vec<String>) -> Result<(), String> {
    let mut family = "routing".to_string();
    let mut name: Option<String> = None;
    let mut dir: Option<PathBuf> = None;
    let mut keep = false;
    let mut score = false;
    let mut date: Option<String> = None;
    let mut catalog = PathBuf::from(CATALOG);
    let mut i = 0;
    let value = |i: usize, flag: &str| args.get(i + 1).cloned().ok_or(format!("{flag} needs a value"));
    while i < args.len() {
        match args[i].as_str() {
            "--family" => {
                family = value(i, "--family")?;
                i += 2;
            }
            "--variant" => {
                name = Some(value(i, "--variant")?);
                i += 2;
            }
            "--dir" => {
                dir = Some(PathBuf::from(value(i, "--dir")?));
                i += 2;
            }
            "--date" => {
                date = Some(value(i, "--date")?);
                i += 2;
            }
            "--catalog" => {
                catalog = PathBuf::from(value(i, "--catalog")?);
                i += 2;
            }
            "--keep" => {
                keep = true;
                i += 1;
            }
            "--score" => {
                score = true;
                i += 1;
            }
            other => return Err(format!("unexpected argument {other:?}")),
        }
    }
    let name = name.ok_or("--variant needs a name")?;
    let v = variant(&family, &name)?;
    let dir = dir.unwrap_or_else(|| {
        if keep || score {
            PathBuf::from(KEEP_DIR)
        } else {
            std::env::temp_dir().join("lbsim-generated")
        }
    });

    if score {
        let date = date.ok_or("--score needs --date YYYY-MM-DD")?;
        return score_kept(v, &dir, &catalog, &date);
    }

    let (path, hash) = write_policy(&dir, v)?;
    println!("{} sha256 {hash}", path.display());
    if !keep {
        return Ok(());
    }

    // The file is in place; the running binary still has yesterday's registry. Rebuild, then let the
    // new binary do the scoring, passing every flag through so the child renders the same source.
    let date = date.ok_or("--keep needs --date YYYY-MM-DD, because simulation code reads no clock")?;
    run("build", Command::new(BUILD).args(["build", "--release", "-p", "sim-run"]))?;
    run(
        "score",
        Command::new(BUILD).args(["run", "--release", "-p", "sim-run", "--", "generate", "--score"]).args([
            "--family",
            &family,
            "--variant",
            &name,
            "--dir",
            &dir.display().to_string(),
            "--date",
            &date,
            "--catalog",
            &catalog.display().to_string(),
        ]),
    )
}

fn score_kept(v: &Variant, dir: &Path, catalog: &Path, date: &str) -> Result<(), String> {
    let path = dir.join(format!("gen_{}.rs", v.name));
    let on_disk = std::fs::read_to_string(&path).map_err(|e| format!("{}: {e}", path.display()))?;
    let hash = sha256_hex(on_disk.as_bytes());
    let expected = sha256_hex(render(v).as_bytes());
    if hash != expected {
        return Err(format!("{}: source differs from the template; regenerate before scoring", path.display()));
    }
    let policies = vec![v.name.to_string()];
    let round = run_round(&policies, &holdout_suite("."), &RoundConfig::default())?;
    let ps = round.ranking.iter().find(|p| p.policy == v.name).ok_or("scored round lacks the policy")?;
    let score = ps.score.ok_or("no load was in scope, so there is no score to catalog")?;
    println!(
        "score {} {score:.4} worst {} mean {:.4} over {} loads",
        v.name,
        ps.worst_load.as_deref().unwrap_or("-"),
        ps.mean_score.unwrap_or(0.0),
        ps.loads_in_scope
    );
    let row = catalog_row(v, &path, &hash, score, date);
    append(catalog, &row)?;
    println!("catalog {} += {}", catalog.display(), row.source);
    Ok(())
}
