//! Generates the policy registry from the policy files themselves.
//!
//! Until 2026-09-06 `src/lib.rs` held the `ROUTING` and `ADMISSION` tables by hand, and three policy
//! branches written in parallel each added "exactly one line" to the same table, which is a guaranteed
//! three-way conflict at integration. Now a policy is one file that declares itself on its first line,
//!
//!     //! lbsim-policy: routing names=p2c,power_of_two_choices
//!     //! lbsim-policy: admission names=accept_all
//!     //! lbsim-policy: health names=none
//!     //! lbsim-policy: scheduling names=fifo_chunked,fcfs
//!     //! lbsim-policy: autoscaling names=target_utilization,target
//!
//! and this script writes `$OUT_DIR/registry.rs` with the `mod` lines and both tables, sorted by file
//! name so the output is deterministic whatever order the directory listing comes back in. A branch that
//! adds a policy touches only its own file; two such branches cannot conflict.
//!
//! Standard library only, like everything else in the workspace.

use std::fmt::Write as _;
use std::fs;
use std::path::Path;

struct Entry {
    module: String,
    file: String,
    kind: String,
    names: Vec<String>,
}

fn parse_header(file: &str, first_line: &str) -> Option<Entry> {
    let rest = first_line.trim().strip_prefix("//! lbsim-policy:")?.trim();
    let mut kind = None;
    let mut names = Vec::new();
    for tok in rest.split_whitespace() {
        if let Some(v) = tok.strip_prefix("names=") {
            names = v.split(',').filter(|s| !s.is_empty()).map(str::to_string).collect();
        } else {
            kind = Some(tok.to_string());
        }
    }
    let kind = kind?;
    if !["routing", "admission", "health", "scheduling", "autoscaling"].contains(&kind.as_str()) {
        panic!("{file}: lbsim-policy kind must be routing, admission, health, scheduling or autoscaling, got {kind:?}");
    }
    if names.is_empty() {
        panic!("{file}: lbsim-policy header needs names=<a,b,...>");
    }
    Some(Entry { module: file.trim_end_matches(".rs").to_string(), file: file.to_string(), kind, names })
}

fn main() {
    let src = Path::new("src");
    println!("cargo:rerun-if-changed=src");
    let mut files: Vec<String> = fs::read_dir(src)
        .expect("src/")
        .filter_map(|e| e.ok())
        .map(|e| e.file_name().to_string_lossy().into_owned())
        .filter(|n| n.ends_with(".rs"))
        .collect();
    files.sort();

    let mut entries = Vec::new();
    for f in &files {
        let text = fs::read_to_string(src.join(f)).expect("policy source");
        let first = text.lines().next().unwrap_or("");
        if let Some(e) = parse_header(f, first) {
            entries.push(e);
        }
    }

    let mut out = String::new();
    writeln!(out, "// Generated by build.rs from the `//! lbsim-policy:` header of each file in src/. Do not edit.").unwrap();
    // `mod x;` inside an `include!`d file resolves relative to OUT_DIR, not src/, so each module names
    // its file explicitly. The manifest directory is absolute, which is fine for a file that lives in
    // the build directory and is regenerated on every build.
    let manifest = std::env::var("CARGO_MANIFEST_DIR").unwrap();
    for e in &entries {
        writeln!(out, "#[path = {:?}]", format!("{manifest}/src/{}", e.file)).unwrap();
        writeln!(out, "mod {};", e.module).unwrap();
    }
    for (kind, ty, doc) in [
        ("routing", "RoutingPolicy", "The routing registry, sorted by file name."),
        ("admission", "AdmissionPolicy", "The admission registry, sorted by file name."),
        ("health", "HealthPolicy", "The health (ejection) registry, sorted by file name."),
        ("scheduling", "SchedulingPolicy", "The scheduling registry, sorted by file name."),
        ("autoscaling", "AutoscalingPolicy", "The autoscaling registry, sorted by file name."),
    ] {
        writeln!(out, "/// {doc}").unwrap();
        writeln!(out, "pub const {}: &[PolicyEntry<dyn {ty}>] = &[", kind.to_uppercase()).unwrap();
        for e in entries.iter().filter(|e| e.kind == kind) {
            let names: Vec<String> = e.names.iter().map(|n| format!("{n:?}")).collect();
            writeln!(
                out,
                "    PolicyEntry {{ names: &[{}], file: {:?}, make: {}::make }},",
                names.join(", "),
                e.file,
                e.module
            )
            .unwrap();
        }
        writeln!(out, "];").unwrap();
    }
    let dest = Path::new(&std::env::var("OUT_DIR").unwrap()).join("registry.rs");
    fs::write(dest, out).unwrap();
}
